### PR TITLE
Give fallbacks for computed styles

### PR DESCRIPTION
**Pull request by bedeoverend**
This resolves issues when the element hasn't been properly painted before asking for the computed style.
Computed style would normally return '', so it falls back to '0px' to stop animations breaking.

### CODE REVIEW

**Comment by seaneking** [comment]
Animations still broken in certain shadow cases (c.f. simpla.io). Don't understand what this fixes? The busy warning is what should stop it asking for computed styles before paint. If you cache 0px then the spinner will look broken. Is this just for tests?

**Comment by bedeoverend** [comment]
This is for tests and any scenario it asks to animate _after_ the spinner has loaded, but _before_ the paint has occured. This breaks tests, and it will probably throw errors in other scenarios too. It doesn't affect the shadow / shady dom scenario.

**Comment by bedeoverend** [comment]
It also won't cache the `0px`

**Comment by seaneking** [comment]
if it asks for busy after spinner loaded but before paint has occured we should warn and not go busy. Giving 0px will look broken.

**Comment by bedeoverend** [comment]
Fair enough - I'll add a check alongside the no spinner check

**Comment by bedeoverend** [comment]
@seaneking adjusted, take another look now

**Pull request merged**
